### ISSUE TITLE
Missing GITHUB_TOKEN in build_addon.yml?

### ISSUE THREAD

**Issue by mo29cg** [nvdaaddons/AddonTemplate#42]
To make a release of an addon from github actions, it needs auth token of github.
Otherwise, it fails.
So, yml file needs to be like this.

```
upload_release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - name: download releases files
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: packaged_addon/*.nvda-addon
          fail_on_unmatched_files: true
          prerelease: ${{ contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

but GITHUB_TOKEN part is not present in
https://github.com/nvdaaddons/AddonTemplate/blob/master/.github/workflows/build_addon.yml

Is there a specific reason not including it?
If not, I'm willing to make a pr.
